name: thanhlq

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/thanhlq
      PORT: 8080
    networks:
      - thanhlq-network

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   restart: always
  #   depends_on:
  #     - backend
  #   ports:
  #     - 80:3000
  #   environment:
  #     BACKEND_URL: http://backend:8080
  #   networks:
  #     - thanhlq-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: thanhlq
    volumes:
      - ./database/data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - thanhlq-network

networks:
  thanhlq-network:
    driver: bridge
