services:
  # backend:
  #   build: ./backend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./backend:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     - mongo
  #   environment:
  #     MONGO_URI: mongodb://mongo:27017/thanhlq

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: thanhlq
    volumes:
      - ./database/data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
